### PR TITLE
Make QEMU from `noble-updates` buildable against `core22` (5.21-edge)

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
In a VM, starting with `5.21/edge` with QEMU `8.2.1` and then refreshing to a locally built snap from this branch:

```
root@v2:~# snap list lxd
Name  Version      Rev    Tracking   Publisher   Notes
lxd   git-7ea3c2b  31537  5.21/edge  canonical✓  -
root@v2:~# lxc info | grep -A1 -w qemu
  driver: lxc | qemu
  driver_version: 6.0.2 | 8.2.1

root@v2:~# snap install --dangerous /dev/shm/lxd_0+git.17a958e2_amd64.snap 
2024-12-04T20:41:44Z INFO Waiting for "snap.lxd.daemon.service" to stop.
lxd 0+git.17a958e2 installed
root@v2:~# snap alias lxd.lxc lxc

root@v2:~# lxc info | grep -A1 -w qemu
  driver: lxc | qemu
  driver_version: 6.0.2 | 8.2.2
  
root@v2:~# snap list | grep core
core22  20241119        1722   latest/stable  canonical**  base
  
root@v2:~# lxc ls
+------+---------+------+------+-----------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+------+---------+------+------+-----------------+-----------+
| av1  | STOPPED |      |      | VIRTUAL-MACHINE | 0         |
+------+---------+------+------+-----------------+-----------+
root@v2:~# lxc start av1
root@v2:~# lxc exec av1 -- hostname
av1
```

**Review by tomponline — APPROVED** [review]
Cool that was a small change in the end then! Thanks

How did you find it?

**Comment by simondeziel** [comment]
> Cool that was a small change in the end then! Thanks

Yeah, the kind I like :)

> How did you find it?

Looking at the git branches generated by the `git-ubuntu` importer, I noticed the vendored wheels were deleted (possibly due to being ~binary blobs (zip files actually)).

Should I backport this to `5.0-edge` to fast-forward the QEMU version to one that's supported?

**Comment by tomponline** [comment]
> Should I backport this to `5.0-edge` to fast-forward the QEMU version to one that's supported?

Yes lets give that a go, thanks!

**Pull request merged**
