### PR TITLE
daemon.start: detect libfuse soname changes for fuse/fuse3

### PR DESCRIPTION
**Pull request by simondeziel**
For https://github.com/canonical/lxd-pkg-snap/pull/214#issuecomment-1847296679

### CODE REVIEW

**Comment by tomponline** [comment]
Could you add a comment to this code explaining what its doing and why its needed. Ta

**Review by mihalicyn — DISMISSED** [review]
LGTM. Thanks!

**Comment by simondeziel** [comment]
@mihalicyn If you don't mind, please take a look at the newly added comments to be sure I understood the purpose of that detection. Thanks

**Review by tomponline — APPROVED** [review]

**Review by tomponline — APPROVED** [review]
Very helpful thanks

**Review by mihalicyn — APPROVED** [review]

**Pull request merged**
