### PR TITLE
lxd-ui: Bump to 0.8.2 (5.21-candidate)

### PR DESCRIPTION
**Pull request by edlerd**
This includes a fix for https://github.com/canonical/lxd-ui/issues/810 preventing an error in network configuration from the ui.

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
Thanks!

**Comment by tomponline** [comment]
@edlerd do we need a similar bump for latest/candidate also?

**Comment by edlerd** [comment]
> @edlerd do we need a similar bump for latest/candidate also?

@tomponline latest/candidate should be fine. It points to the 0.9 tag of the ui. And 0.9 includes the fix already. I just got aware today that the 0.8.1 was missing this one and created 0.8.2 through the new bug report.

Thanks for merging this shortly :)

**Comment by tomponline** [comment]
Perfect thanks!

**Pull request merged**
