### PR TITLE
snapcraft: lxcfs: cherry-pick upstream bugfix (5.21-edge)

### PR DESCRIPTION
**Pull request by mihalicyn**

### CODE REVIEW

**Review by simondeziel — APPROVED** [review]

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
Sorry we don't need the cherry pick or this charge on the edge branches as I've just seen they pull from lxcfs head anyway . we only need to cherry pick on latest-candidate and 5.21-candidate. My bad sorry

**Comment by tomponline** [comment]
Can you repurpose this PR to remove cherry pick please

**Comment by tomponline** [comment]
We only need to cherry pick things when the source is using a specific tag

**Comment by tomponline** [comment]
Closing in favor of https://github.com/canonical/lxd-pkg-snap/pull/398

**Pull request closed without merging**
