### PR TITLE
bump snapd version requirement to 2.65 and remove hacky workaround

### PR DESCRIPTION
**Pull request by mihalicyn**
snapd 2.65 is not released yet. We are waiting for it and:
https://github.com/snapcore/snapd/pull/14118
to be included

### CODE REVIEW

**Comment by mihalicyn** [comment]
Today I've got:
```
$ snap list | grep snapd
snapd                      2.65.3               22991  latest/stable       canonical**         snapd
```
on my system. We can now merge this PR.

**Comment by simondeziel** [comment]
Same here, `snapd` 2.65 was brought by today's refresh. However, we still haven't got a reply from snapd folks about bumping the requirement as asked in (https://github.com/canonical/lxd-pkg-snap/pull/277#discussion_r1465296565). I'll ping them on MM.

**Review by tomponline — APPROVED** [review]
Lets see how this goes this time.

**Comment by simondeziel** [comment]
> Same here, `snapd` 2.65 was brought by today's refresh.

Today, `snapd` 2.65 reached archive's `-updates` and `-security` so we should have no problem reintroducing 
commits ff8df89229a6ded76151dbe5045e7263e97a4116 and 005d24917d421fa3f96e58f1382f27cac73b080 soon.

Commit 25ca3a1831bf30339210bc4afe83d88afe55a506 is unfortunately another story due to it introducing https://github.com/canonical/lxd/issues/14258

**Comment by tomponline** [comment]
> > Same here, `snapd` 2.65 was brought by today's refresh.
> 
> Today, `snapd` 2.65 reached archive's `-updates` and `-security` so we should have no problem reintroducing commits [ff8df89](https://github.com/canonical/lxd-pkg-snap/commit/ff8df89229a6ded76151dbe5045e7263e97a4116) and [005d249](https://github.com/canonical/lxd-pkg-snap/commit/005d24917d421fa3f96e58f1382f27cac73b080e) soon.
> 
> Commit [25ca3a1](https://github.com/canonical/lxd-pkg-snap/commit/25ca3a1831bf30339210bc4afe83d88afe55a506) is unfortunately another story due to it introducing [canonical/lxd#14258](https://github.com/canonical/lxd/issues/14258)

I'm going to hold off until snapd snap is at 2.65 too and the dust has settled.

**Pull request merged**
