### PR TITLE
lxd-ui: bump to 0.14 (latest-candidate) 

### PR DESCRIPTION
**Pull request by edlerd**
* include recent changes in preparation of 6.2, see https://github.com/canonical/lxd-ui/releases/tag/0.14 for changes

### CODE REVIEW

**Comment by tomponline** [comment]
> * include recent changes in preparation of 6.2, see https://github.com/canonical/lxd-ui/releases/tag/0.14 for changes

Is it right the changelog on https://github.com/canonical/lxd-ui/releases/tag/0.14 is comparing back to 0.12 rather than 0.13?

**Review by tomponline — APPROVED** [review]

**Comment by edlerd** [comment]
> > * include recent changes in preparation of 6.2, see https://github.com/canonical/lxd-ui/releases/tag/0.14 for changes
> 
> Is it right the changelog on https://github.com/canonical/lxd-ui/releases/tag/0.14 is comparing back to 0.12 rather than 0.13?

Yes, 0.13 was not released yet.

**Comment by tomponline** [comment]
> Yes, 0.13 was not released yet.

Yet?

**Comment by edlerd** [comment]
> > Yes, 0.13 was not released yet.
> 
> Yet?

We're skipping the 0.13 release as 0.14 will be tied to 6.2 and 0.12 was shipped with 6.1. Sorry my previous statement was a bit confusing. I'd like to skip the unlucky number :)

**Pull request merged**
