### PR TITLE
Replace snap-query (Go) by python implementation

### PR DESCRIPTION
**Pull request by simondeziel**
This python implementation leverages the fact that python3 is shipped in the base core snap and avoids shipping the Go version of snap-query that was ~4.7MiB once compiled and stripped.

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
What about using jq?

**Comment by simondeziel** [comment]
Nah, `jq` isn't in the base snap, `python3` is though.

**Comment by tomponline** [comment]
We could add it though? Would be smaller than the go program no?

**Comment by tomponline** [comment]
Ah but Python is available I see

**Comment by tomponline** [comment]
I would prefer correct over brittle tbh

**Comment by simondeziel** [comment]
The go and python implementation were tested manually by comparing their output while doing:

* snap stop lxd
* snap start lxd
* snap restart lxd
* snap revert lxd
* snap refresh lxd --channel latest/stable
* systemctl stop snap.lxd.daemon

In all cases, the output was identical and what was logged by `daemon.stop` the same.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
