### PR TITLE
snapcraft: edk2: update logo

### PR DESCRIPTION
**Pull request by mihalicyn**
```
Converted from "LXD tags@2x.png" using:
$ convert -scale 60% -colors 256 -depth 8 -type palette -compress none LXD\ tags@2x.png BMP3:edk2-0002-logo.bmp
```

### CODE REVIEW

**Comment by tomponline** [comment]
@mihalicyn does it work with a rectangular logo or do we need to crop it to be square?

**Comment by mihalicyn** [comment]
> @mihalicyn does it work with a rectangular logo or do we need to crop it to be square?

The previous image also wasn't a perfect square. But right now I'm testing this change together with the edk2 version update ;-)

**Comment by tomponline** [comment]
> > @mihalicyn does it work with a rectangular logo or do we need to crop it to be square?
> 
> The previous image also wasn't a perfect square. But right now I'm testing this change together with the edk2 version update ;-)

If it looks OK im happy with using he image as it is.

**Comment by mihalicyn** [comment]
It works perfectly fine now. One extra fix was needed for the image.
I have added a `-compress none` as EDKII does not support compressed bmp files.

**Comment by mihalicyn** [comment]
Safe to merge.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
