### PR TITLE
include lxcfs pidfd into lxd snap configuration

### PR DESCRIPTION
**Pull request by monkz**
Enable the user to use pidfd support in lxcfs via snap configuration of lxd

### CODE REVIEW

**Comment by stgraber** [comment]
The description in snapcraft.yaml reads as a bit redundant

**Comment by stgraber** [comment]
Start tracking ... tracking

**Comment by monkz** [comment]
Redundancy reduced redundancy

**Comment by stgraber** [comment]
thanks!

**Pull request merged**
