### PR TITLE
snapcraft: use SNAPCRAFT_PRIME instead of CRAFT_PRIME (5.0-edge)

### PR DESCRIPTION
**Pull request by mihalicyn**
Fixup for the previous commit.

### CODE REVIEW

**Review by simondeziel — APPROVED** [review]
Right, that's needed until we move to core22, sigh. Thanks

**Comment by mihalicyn** [comment]
This failure looks suspicious https://github.com/canonical/lxd-pkg-snap/actions/runs/9500461141/job/26183599965

**Comment by simondeziel** [comment]
> This failure looks suspicious https://github.com/canonical/lxd-pkg-snap/actions/runs/9500461141/job/26183599965

It's just missing the same as https://github.com/canonical/lxd-pkg-snap/pull/448

**Review by tomponline — COMMENTED** [review]
5.0/edge is on core22 though

**Comment by simondeziel** [comment]
Good point re core22 for 5.0/edge. However I think it's best to keep those variables uniform until we can do the mass `sed`.

**Pull request merged**
