### PR TITLE
WIP: edk2: Bump to 202308

### LINKED ISSUE #12166: Remove edk patch from snap once next stable release is out
See https://github.com/tianocore/edk2/commit/c1e853769046b322690ad336fdb98966757e7414

See also https://github.com/canonical/lxd-pkg-snap/pull/134#issuecomment-1684006511

### PR DESCRIPTION
**Pull request by mihalicyn**
Fixes https://github.com/canonical/lxd/issues/12166

Not ready yet as I need to solve a build issue:
```
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:46.988 :: ###
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:46.988 :: Generating DXEFV FV
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.970 :: ########### ['GenFv', '-a', '/root/parts/edk2/build/Build/OvmfX64/RELEASE_GCC5/FV/Ffs/FVMAIN_COMPACT.inf', '-o', '/root/parts/edk2/build/Build/OvmfX64/RELEASE_GCC5/FV/FVMAIN_COMPACT.Fv', '-i', '/root/parts/edk2/build/Build/OvmfX64/RELEASE_GCC5/FV/FVMAIN_COMPACT.inf']
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.970 :: Return Value = 2
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.970 :: GenFv: ERROR 3000: Invalid
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.970 ::   the required fv image size 0x1b9180 exceeds the set fv image size 0x1ac000
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.970 ::
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.971 ::
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.971 ::
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.971 ::
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.971 :: build.py...
2023-09-01 14:28:49.855 :: 2023-09-01 12:28:48.971 ::  : error 7000: Failed to generate FV
```

### CODE REVIEW

**Comment by mihalicyn** [comment]
Most likely size of the firmware increased after https://github.com/tianocore/edk2/commit/ff3382a51ca726a90f49623a2b2d2e8ad8459ce2
Will need to experiment with this thing more.

`0x1ac000` is a standard FV block size for 2MiB firmware:
https://github.com/tianocore/edk2/blob/beafabdae49c873adecdb7511dbebe9d4ff5c8f0/OvmfPkg/Include/Fdf/OvmfPkgDefines.fdf.inc#L48

We fail on 2MiB firmware which does not include CSM blob.

This allows to build 2MiB image:
```
       build_edk2 \
         "${CRAFT_PART_INSTALL}/share/qemu/OVMF_CODE.2MB.fd" \
         "${CRAFT_PART_INSTALL}/share/qemu/OVMF_VARS.2MB.fd" \
-        -DFD_SIZE_2MB
+        -DFD_SIZE_2MB \
+        -DNETWORK_ISCSI_ENABLE=FALSE \
+        -DBUILD_SHELL=FALSE
       ln -s OVMF_CODE.2MB.fd ${CRAFT_PART_INSTALL}/share/qemu/OVMF_CODE.fd
       ln -s OVMF_VARS.2MB.fd ${CRAFT_PART_INSTALL}/share/qemu/OVMF_VARS.fd
```

I don't think that we need to build iSCSI support in UEFI firmware (we don't use iSCSI as far as I understand).
But I'm not sure about UEFI Shell. Nobody uses it in 99% cases, but...

As an alternative we can build 4MB blob from the new version of edk2, and 2MB from the old one.

**Comment by simondeziel** [comment]
IIRC the UEFI shell was sometimes mentioned in forum posts for debugging issues with booting Windows from an ISO.

As for the iSCSI support, it sounds reasonable to drop and I'd vote to drop it from all build variants, not just the 2MiB one.

**Comment by tomponline** [comment]
Yeah let's drop iscsi from all variants

**Comment by tomponline** [comment]
Any other features we can drop?

**Comment by simondeziel** [comment]
We might be able to reclaim some space by disabling TPM1 support (`-DTPM1_ENABLE=FALSE`) but I'm not sure if (existing) LXD VMs would be affected.

**Comment by tomponline** [comment]
Whilst replying to 

https://discourse.ubuntu.com/t/lxd-vm-agent-fails-to-come-online-with-lxd-5-15-and-large-vm-resource-requirements/37963/12

I noticed that we had some TPM disable flags in the past on edk2 as well:

https://github.com/canonical/lxd-pkg-snap/commit/dadf771712cd09d0548bd1e4dfd0080626b9c4c5

**Comment by mihalicyn** [comment]
> I noticed that we had some TPM disable flags in the past on edk2 as well:

yes, at the same time, both `TPM_ENABLE` and `TPM_CONFIG_ENABLE` are not existing in the edk2 code-base anymore.
https://github.com/tianocore/edk2/commit/4de8d61bcec02a13ceed84f92b0cf3ea58adf9c5

As far as I can see `TPM1_ENABLE` is `TRUE` by default.

**Comment by tomponline** [comment]
@mihalicyn will you be able to pick this back up after we remove the CSM support as per https://github.com/canonical/lxd/issues/12730

**Pull request closed without merging**
