### PR TITLE
[WIP] snapcraft: add apparmor part for core22 only (5.0-edge)

### PR DESCRIPTION
**Pull request by mihalicyn**
Let's ship newer version of AppArmor with support of new features. Only needed for core22.

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
We shouldn't need this for latest edge as you just switched that to core24. Instead this pr should target the 5.0 edge branch which is being transitioned to core22 by @simondeziel

**Comment by mihalicyn** [comment]
yes, of course. I just decided to keep it there so we can discuss it. Also, I had to add some support to LXD to choose this LXD-snap-shipped version instead of the default provided in core22. So, it is a work in progress for now.

**Comment by tomponline** [comment]
> yes, of course. I just decided to keep it there so we can discuss it. Also, I had to add some support to LXD to choose this LXD-snap-shipped version instead of the default provided in core22. So, it is a work in progress for now.

OK I'll wait for your update, although I am concerned about having to modify LXD, can we avoid that by doing changes in the snap to set the PATH to the apparmor parser? 

Anyway I'll wait until I can see what you're getting at :)

**Comment by mihalicyn** [comment]
> OK I'll wait for your update, although I am concerned about having to modify LXD, can we avoid that by doing changes in the snap to set the PATH to the apparmor parser?

you are absolutely right. It just works with current `PATH` variable value ;-)

**Pull request closed without merging**
