### PR TITLE
Make `lvm.conf` patching work with `lvm2` from 24.04

### LINKED ISSUE #14341: Performance regression with `lvm` (non-thin) on `latest/edge` snap
It's been a while since we noticed that `tests/storage-vm lvm` from lxd-ci is much slower with `latest/edge` than it is with `5.21/edge`.

Here are some logs taken from CI runs comparing the 2 snap channels.

`storage-vm lvm (latest/edge - 24.04)` taking ~44 minutes to complete:

```
==> Checking VM can be migrated with snapshots (different storage pool)
+ lxc copy v1 localhost:v2 -s vmpool-lvm-33922 --stateless
Transferring instance: v2/snap0: 82.51MB (82.50MB/s)
Transferring instance: v2/snap0: 163.06MB (81.51MB/s)
Transferring instance: v2/snap0: 243.90MB (81.29MB/s)
...
Transferring instance: v2/snap0: 3.53GB (233.38MB/s)                                                    
Transferring instance: v2: 785.26MB (785.25MB/s)
...
Transferring instance: v2: 3.60GB (449.27MB/s)
```

`storage-vm lvm (5.21/edge - 24.04)` taking ~24 minutes to complete:

```
==> Checking VM can be migrated with snapshots (different storage pool)
+ lxc copy v1 localhost:v2 -s vmpool-lvm-34072 --stateless
Transferring instance: v2/snap0: 315.72MB (315.72MB/s)
Transferring instance: v2/snap0: 631.64MB (315.82MB/s)
...
Transferring instance: v2/snap0: 3.68GB (73.25MB/s)                                                   
Transferring instance: v2: 745.92MB (745.91MB/s)
...
Transferring instance: v2: 3.55GB (317.22MB/s)
```

In both cases, we see that transferring `v2/snap0` is much slower than transferring `v2` itself. However, in the `latest/edge` case, the snapshot transfer is noticeably slower than that of `5.21/edge`.

In those 2 CI runs, the GHA runners are using the exact same [`24.04`](https://github.com/actions/runner-images/blob/ubuntu24/20241016.1/images/ubuntu/Ubuntu2404-Readme.md) image. This means only LXD's snap and its `core2X` base differ. `5.21/edge` uses `core22` while `latest/edge` uses `core24`. To rule out a `lvm2` version issue, I used `lvm.external=true` in https://github.com/canonical/lxd-ci/pull/328 and got identical results which seems to indicate a potential regression introduced in LXD between `stable-5.21` and `main`.

One way to compare CI logs is to **download raw logs** from [storage-vm lvm (latest/edge - 24.04)](https://github.com/canonical/lxd-ci/actions/runs/11494020161/job/31990781755#logs) and [storage-vm lvm (5.21/edge - 24.04)](https://github.com/canonical/lxd-ci/actions/runs/11494020161/job/31990789816#logs). Once downloaded, they can be stripped of their datestamp prefix with `sed`:

```
$ sed 's/^[^Z]\+Z //' lvm-latest.raw > lvm-latest.txt
$ sed 's/^[^Z]\+Z //' lvm-521.raw > lvm-521.txt
```

And then `meld` allows to compare them line by line (`meld lvm-latest.txt lvm-521.txt`). This is with this method that I extracted the log snippets from above. Both the `.raw` and `.txt` files are included in the [attached tarball](https://github.com/user-attachments/files/17514423/storage-vm-lvm-logs.tgz.txt). Due to GH policy, `.tgz` files cannot be attached so I added a `.txt` placeholder.

### PR DESCRIPTION
**Pull request by simondeziel**
Fixes https://github.com/canonical/lxd/issues/14341

### CODE REVIEW

**Comment by simondeziel** [comment]
The change is already deployed and confirm to not break anything.

**Review by tomponline — APPROVED** [review]
Thanks!

**Comment by simondeziel** [comment]
> The change is already deployed and confirm to not break anything.

This was meant to go in a different PR. I've not tested those LVM changes very thoroughly. I'll quickly look into this. Sorry

**Comment by simondeziel** [comment]
It seems that only the exec path to `dmeventd` was not properly covered:

```
root@v1:~# LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/:/snap/lxd/current/zfs-2.2/lib PATH=/snap/lxd/current/zfs-2.2/bin:$PATH nsenter --mount=/run/snapd/ns/lxd.mnt -- grep -E '^\s*(udev_(sync|rules)|monitoring) |executable =' /etc/lvm/lvm.conf
	thin_check_executable = "/snap/lxd/31013/bin/thin_check"
	thin_dump_executable = "/snap/lxd/31013/bin/thin_dump"
	thin_repair_executable = "/snap/lxd/31013/bin/thin_repair"
	cache_check_executable = "/snap/lxd/31013/bin/cache_check"
	cache_dump_executable = "/snap/lxd/31013/bin/cache_dump"
	cache_repair_executable = "/snap/lxd/31013/bin/cache_repair"
	vdo_format_executable = "/snap/lxd/31013/bin/vdoformat"
	fsadm_executable = "/snap/lxd/31013/bin/fsadm"
	udev_sync = 0
	udev_rules = 0
	monitoring = 0
	# executable = "/snap/lxd/31013/bin/dmeventd"
```

Unfortunately, the `udev_sync`, `udev_rules` and `monitoring` changes didn't seem to have recovered any performance :/

**Pull request merged**
