### PR TITLE
MicroOVN content interface support

### PR DESCRIPTION
**Pull request by masnax**
Pending the PR in MicroOVN, this adds support for the `ovn-conf` content interface in LXD.

This will fix the issue of needing to restart LXD to pick up an OVN install, so LXD can detect as soon as MicroOVN is installed or removed, and update its symlinks appropriately.

The conditions and paths to the symlinks in `daemon.start` have also been updated to check for the existence of the created content interface directory, rather than the `SNAP_COMMON` directory of the respective snaps.

### CODE REVIEW

**Comment by tomponline** [comment]
@masnax please can you link to the pending PR for microovn so we can monitor that before merging this?

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
@masnax is it possible to merge this without breaking microovn support before the content interface is added to microovn?

**Comment by masnax** [comment]
@tomponline I dropped the commit that would break support until MicroOVN merges and backports the required changes. So now this can be merged.

**Comment by masnax** [comment]
Here's the MicroOVN PR: https://github.com/canonical/microovn/pull/107

**Review by tomponline — APPROVED** [review]

**Pull request merged**
